server:
  port: 8600
#  servlet:
#    context-path: /api

spring:
  main:
    lazy-initialization: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring-mongo
      username: spring-mongo-user
      password: 123456
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        hbm2ddl:
#          auto: none
#        show_sql: false
#        format_sql: false
#        use_sql_comments: false
#    open-in-view: false
#  h2:
#    console:
#      enabled: false
#  sql:
#    init:
#      data-locations: classpath:schema.sql
#      mode: never
jwt:
  secret: todayismondayMarch13rdandistayathometodosomepractice